# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ir_post_v2.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PostProcessIR(object):
    def setupUi(self, PostProcessIR):
        PostProcessIR.setObjectName("PostProcessIR")
        PostProcessIR.resize(1218, 769)
        self.layoutWidget_2 = QtWidgets.QWidget(PostProcessIR)
        self.layoutWidget_2.setGeometry(QtCore.QRect(411, 40, 771, 631))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.dispLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.dispLayout.setContentsMargins(0, 0, 0, 0)
        self.dispLayout.setObjectName("dispLayout")
        self.label_14 = QtWidgets.QLabel(PostProcessIR)
        self.label_14.setGeometry(QtCore.QRect(390, 10, 121, 17))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(0, 17))
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.dispSelectedFile = QtWidgets.QLabel(PostProcessIR)
        self.dispSelectedFile.setGeometry(QtCore.QRect(530, 10, 1000, 17))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dispSelectedFile.sizePolicy().hasHeightForWidth())
        self.dispSelectedFile.setSizePolicy(sizePolicy)
        self.dispSelectedFile.setMinimumSize(QtCore.QSize(601, 17))
        self.dispSelectedFile.setMaximumSize(QtCore.QSize(16777215, 17))
        self.dispSelectedFile.setObjectName("dispSelectedFile")
        self.layoutWidget_3 = QtWidgets.QWidget(PostProcessIR)
        self.layoutWidget_3.setGeometry(QtCore.QRect(410, 680, 771, 67))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.sl = QtWidgets.QSlider(self.layoutWidget_3)
        self.sl.setEnabled(False)
        self.sl.setMinimumSize(QtCore.QSize(739, 0))
        self.sl.setOrientation(QtCore.Qt.Horizontal)
        self.sl.setObjectName("sl")
        self.verticalLayout_3.addWidget(self.sl)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.slStartF = QtWidgets.QLabel(self.layoutWidget_3)
        self.slStartF.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.slStartF.setObjectName("slStartF")
        self.horizontalLayout_5.addWidget(self.slStartF)
        self.slMidF = QtWidgets.QLabel(self.layoutWidget_3)
        self.slMidF.setAlignment(QtCore.Qt.AlignCenter)
        self.slMidF.setObjectName("slMidF")
        self.horizontalLayout_5.addWidget(self.slMidF)
        self.slEndF = QtWidgets.QLabel(self.layoutWidget_3)
        self.slEndF.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.slEndF.setObjectName("slEndF")
        self.horizontalLayout_5.addWidget(self.slEndF)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.slStartT = QtWidgets.QLabel(self.layoutWidget_3)
        self.slStartT.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.slStartT.setObjectName("slStartT")
        self.horizontalLayout_3.addWidget(self.slStartT)
        self.slMidT = QtWidgets.QLabel(self.layoutWidget_3)
        self.slMidT.setAlignment(QtCore.Qt.AlignCenter)
        self.slMidT.setObjectName("slMidT")
        self.horizontalLayout_3.addWidget(self.slMidT)
        self.slEndT = QtWidgets.QLabel(self.layoutWidget_3)
        self.slEndT.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.slEndT.setObjectName("slEndT")
        self.horizontalLayout_3.addWidget(self.slEndT)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.layoutWidget = QtWidgets.QWidget(PostProcessIR)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 381, 741))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.selectFileBut = QtWidgets.QPushButton(self.layoutWidget)
        self.selectFileBut.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.selectFileBut.setFont(font)
        self.selectFileBut.setObjectName("selectFileBut")
        self.verticalLayout.addWidget(self.selectFileBut)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cmIronBut = QtWidgets.QPushButton(self.layoutWidget)
        self.cmIronBut.setObjectName("cmIronBut")
        self.horizontalLayout_4.addWidget(self.cmIronBut)
        self.cmGrayBut = QtWidgets.QPushButton(self.layoutWidget)
        self.cmGrayBut.setObjectName("cmGrayBut")
        self.horizontalLayout_4.addWidget(self.cmGrayBut)
        self.cmRainBut = QtWidgets.QPushButton(self.layoutWidget)
        self.cmRainBut.setObjectName("cmRainBut")
        self.horizontalLayout_4.addWidget(self.cmRainBut)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.playVidBut = QtWidgets.QPushButton(self.layoutWidget)
        self.playVidBut.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playVidBut.sizePolicy().hasHeightForWidth())
        self.playVidBut.setSizePolicy(sizePolicy)
        self.playVidBut.setObjectName("playVidBut")
        self.horizontalLayout_9.addWidget(self.playVidBut)
        self.pauseVidBut = QtWidgets.QPushButton(self.layoutWidget)
        self.pauseVidBut.setEnabled(False)
        self.pauseVidBut.setObjectName("pauseVidBut")
        self.horizontalLayout_9.addWidget(self.pauseVidBut)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.rotButton = QtWidgets.QPushButton(self.layoutWidget)
        self.rotButton.setEnabled(False)
        self.rotButton.setObjectName("rotButton")
        self.verticalLayout.addWidget(self.rotButton)
        self.nextFrame = QtWidgets.QPushButton(self.layoutWidget)
        self.nextFrame.setEnabled(False)
        self.nextFrame.setObjectName("nextFrame")
        self.verticalLayout.addWidget(self.nextFrame)
        self.prevFrame = QtWidgets.QPushButton(self.layoutWidget)
        self.prevFrame.setEnabled(False)
        self.prevFrame.setObjectName("prevFrame")
        self.verticalLayout.addWidget(self.prevFrame)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.startEdit.setEnabled(False)
        self.startEdit.setText("")
        self.startEdit.setObjectName("startEdit")
        self.horizontalLayout.addWidget(self.startEdit)
        self.stopEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.stopEdit.setEnabled(False)
        self.stopEdit.setText("")
        self.stopEdit.setObjectName("stopEdit")
        self.horizontalLayout.addWidget(self.stopEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.saveAsVideoSS = QtWidgets.QPushButton(self.layoutWidget)
        self.saveAsVideoSS.setEnabled(False)
        self.saveAsVideoSS.setObjectName("saveAsVideoSS")
        self.verticalLayout.addWidget(self.saveAsVideoSS)
        self.tempScaleBut = QtWidgets.QPushButton(self.layoutWidget)
        self.tempScaleBut.setEnabled(False)
        self.tempScaleBut.setObjectName("tempScaleBut")
        self.verticalLayout.addWidget(self.tempScaleBut)
        self.saveCvImageBut = QtWidgets.QPushButton(self.layoutWidget)
        self.saveCvImageBut.setEnabled(False)
        self.saveCvImageBut.setObjectName("saveCvImageBut")
        self.verticalLayout.addWidget(self.saveCvImageBut)
        self.makeTiffBut = QtWidgets.QPushButton(self.layoutWidget)
        self.makeTiffBut.setEnabled(False)
        self.makeTiffBut.setObjectName("makeTiffBut")
        self.verticalLayout.addWidget(self.makeTiffBut)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.displayC = QtWidgets.QPushButton(self.layoutWidget)
        self.displayC.setEnabled(False)
        self.displayC.setObjectName("displayC")
        self.horizontalLayout_7.addWidget(self.displayC)
        self.displayF = QtWidgets.QPushButton(self.layoutWidget)
        self.displayF.setEnabled(False)
        self.displayF.setObjectName("displayF")
        self.horizontalLayout_7.addWidget(self.displayF)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.cursorTempLabel = QtWidgets.QLabel(self.layoutWidget)
        self.cursorTempLabel.setObjectName("cursorTempLabel")
        self.verticalLayout.addWidget(self.cursorTempLabel)
        self.maxTempLabel = QtWidgets.QLabel(self.layoutWidget)
        self.maxTempLabel.setObjectName("maxTempLabel")
        self.verticalLayout.addWidget(self.maxTempLabel)
        self.maxTempLocLabel = QtWidgets.QLabel(self.layoutWidget)
        self.maxTempLocLabel.setObjectName("maxTempLocLabel")
        self.verticalLayout.addWidget(self.maxTempLocLabel)
        self.minTempLabel = QtWidgets.QLabel(self.layoutWidget)
        self.minTempLabel.setObjectName("minTempLabel")
        self.verticalLayout.addWidget(self.minTempLabel)
        self.minTempLocLabel = QtWidgets.QLabel(self.layoutWidget)
        self.minTempLocLabel.setObjectName("minTempLocLabel")
        self.verticalLayout.addWidget(self.minTempLocLabel)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.currentFrameDisp = QtWidgets.QLabel(self.layoutWidget)
        self.currentFrameDisp.setObjectName("currentFrameDisp")
        self.verticalLayout.addWidget(self.currentFrameDisp)
        self.currentTimeLabel = QtWidgets.QLabel(self.layoutWidget)
        self.currentTimeLabel.setObjectName("currentTimeLabel")
        self.verticalLayout.addWidget(self.currentTimeLabel)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.history = QtWidgets.QPlainTextEdit(self.layoutWidget)
        self.history.setObjectName("history")
        self.verticalLayout_2.addWidget(self.history)

        self.retranslateUi(PostProcessIR)
        QtCore.QMetaObject.connectSlotsByName(PostProcessIR)

    def retranslateUi(self, PostProcessIR):
        _translate = QtCore.QCoreApplication.translate
        PostProcessIR.setWindowTitle(_translate("PostProcessIR", "Dialog"))
        self.label_14.setText(_translate("PostProcessIR", "File Selected: "))
        self.dispSelectedFile.setText(_translate("PostProcessIR", "Use Select File Button"))
        self.slStartF.setText(_translate("PostProcessIR", "Please Select File"))
        self.slMidF.setText(_translate("PostProcessIR", "Please Select File"))
        self.slEndF.setText(_translate("PostProcessIR", "Please Select File"))
        self.slStartT.setText(_translate("PostProcessIR", "Please Select File"))
        self.slMidT.setText(_translate("PostProcessIR", "Please Select File"))
        self.slEndT.setText(_translate("PostProcessIR", "Please Select File"))
        self.selectFileBut.setText(_translate("PostProcessIR", "Select HDF5 File"))
        self.cmIronBut.setText(_translate("PostProcessIR", "Ironblack"))
        self.cmGrayBut.setText(_translate("PostProcessIR", "Grayscale"))
        self.cmRainBut.setText(_translate("PostProcessIR", "Rainbow"))
        self.playVidBut.setText(_translate("PostProcessIR", "Play Video"))
        self.pauseVidBut.setText(_translate("PostProcessIR", "Pause Video"))
        self.rotButton.setText(_translate("PostProcessIR", "Rotate"))
        self.nextFrame.setText(_translate("PostProcessIR", "Next Frame"))
        self.prevFrame.setText(_translate("PostProcessIR", "Previous Frame"))
        self.label_10.setText(_translate("PostProcessIR", "Start Frame:"))
        self.label_11.setText(_translate("PostProcessIR", "Stop Frame:"))
        self.saveAsVideoSS.setText(_translate("PostProcessIR", "Save AVI Video from Start to Stop Frame"))
        self.tempScaleBut.setText(_translate("PostProcessIR", "Generate Figure with Temp Scale"))
        self.saveCvImageBut.setText(_translate("PostProcessIR", "Save PNG Image (Without Axes)"))
        self.makeTiffBut.setText(_translate("PostProcessIR", "Generate Tiff File (Full Duration)"))
        self.displayC.setText(_translate("PostProcessIR", "Display Celsius"))
        self.displayF.setText(_translate("PostProcessIR", "Display Fahrenheit"))
        self.cursorTempLabel.setText(_translate("PostProcessIR", "Cursor Temp:"))
        self.maxTempLabel.setText(_translate("PostProcessIR", "Current Max Temp:"))
        self.maxTempLocLabel.setText(_translate("PostProcessIR", "Max Temp Loc:"))
        self.minTempLabel.setText(_translate("PostProcessIR", "Current Min Temp: "))
        self.minTempLocLabel.setText(_translate("PostProcessIR", "Min Temp Loc:"))
        self.currentFrameDisp.setText(_translate("PostProcessIR", "Current Frame:"))
        self.currentTimeLabel.setText(_translate("PostProcessIR", "Current Time:"))
        self.label.setText(_translate("PostProcessIR", "Command Log:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PostProcessIR = QtWidgets.QDialog()
    ui = Ui_PostProcessIR()
    ui.setupUi(PostProcessIR)
    PostProcessIR.show()
    sys.exit(app.exec_())

