# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ir_v11.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1007, 686)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.displayFrame = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayFrame.sizePolicy().hasHeightForWidth())
        self.displayFrame.setSizePolicy(sizePolicy)
        self.displayFrame.setMinimumSize(QtCore.QSize(640, 480))
        self.displayFrame.setAlignment(QtCore.Qt.AlignCenter)
        self.displayFrame.setObjectName("displayFrame")
        self.gridLayout.addWidget(self.displayFrame, 0, 0, 2, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 1, 2, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.startStreamBut = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.startStreamBut.setFont(font)
        self.startStreamBut.setObjectName("startStreamBut")
        self.horizontalLayout_5.addWidget(self.startStreamBut)
        self.ffcBut = QtWidgets.QPushButton(self.centralwidget)
        self.ffcBut.setEnabled(True)
        self.ffcBut.setObjectName("ffcBut")
        self.horizontalLayout_5.addWidget(self.ffcBut)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.comboGain = QtWidgets.QComboBox(self.centralwidget)
        self.comboGain.setEnabled(True)
        self.comboGain.setObjectName("comboGain")
        self.comboGain.addItem("")
        self.comboGain.addItem("")
        self.comboGain.addItem("")
        self.horizontalLayout_3.addWidget(self.comboGain)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.comboFFCmode = QtWidgets.QComboBox(self.centralwidget)
        self.comboFFCmode.setEnabled(True)
        self.comboFFCmode.setObjectName("comboFFCmode")
        self.comboFFCmode.addItem("")
        self.comboFFCmode.addItem("")
        self.comboFFCmode.addItem("")
        self.horizontalLayout_6.addWidget(self.comboFFCmode)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_4.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.filePathBut = QtWidgets.QPushButton(self.centralwidget)
        self.filePathBut.setObjectName("filePathBut")
        self.verticalLayout.addWidget(self.filePathBut)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.startRec = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.startRec.setFont(font)
        self.startRec.setObjectName("startRec")
        self.verticalLayout_2.addWidget(self.startRec)
        self.stopRec = QtWidgets.QPushButton(self.centralwidget)
        self.stopRec.setObjectName("stopRec")
        self.verticalLayout_2.addWidget(self.stopRec)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.recLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.recLabel.setFont(font)
        self.recLabel.setObjectName("recLabel")
        self.horizontalLayout.addWidget(self.recLabel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.displayC = QtWidgets.QPushButton(self.centralwidget)
        self.displayC.setObjectName("displayC")
        self.horizontalLayout_2.addWidget(self.displayC)
        self.displayF = QtWidgets.QPushButton(self.centralwidget)
        self.displayF.setObjectName("displayF")
        self.horizontalLayout_2.addWidget(self.displayF)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.timeStatus = QtWidgets.QLabel(self.centralwidget)
        self.timeStatus.setObjectName("timeStatus")
        self.verticalLayout.addWidget(self.timeStatus)
        self.cursorTempLabel = QtWidgets.QLabel(self.centralwidget)
        self.cursorTempLabel.setObjectName("cursorTempLabel")
        self.verticalLayout.addWidget(self.cursorTempLabel)
        self.maxTempLabel = QtWidgets.QLabel(self.centralwidget)
        self.maxTempLabel.setObjectName("maxTempLabel")
        self.verticalLayout.addWidget(self.maxTempLabel)
        self.minTempLabel = QtWidgets.QLabel(self.centralwidget)
        self.minTempLabel.setObjectName("minTempLabel")
        self.verticalLayout.addWidget(self.minTempLabel)
        self.storageLabel = QtWidgets.QLabel(self.centralwidget)
        self.storageLabel.setObjectName("storageLabel")
        self.verticalLayout.addWidget(self.storageLabel)
        self.runPost = QtWidgets.QPushButton(self.centralwidget)
        self.runPost.setObjectName("runPost")
        self.verticalLayout.addWidget(self.runPost)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout.addLayout(self.verticalLayout, 0, 2, 1, 1)
        self.history = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.history.sizePolicy().hasHeightForWidth())
        self.history.setSizePolicy(sizePolicy)
        self.history.setMaximumSize(QtCore.QSize(16777215, 87))
        self.history.setObjectName("history")
        self.gridLayout.addWidget(self.history, 1, 2, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.labelForLocation = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelForLocation.sizePolicy().hasHeightForWidth())
        self.labelForLocation.setSizePolicy(sizePolicy)
        self.labelForLocation.setMinimumSize(QtCore.QSize(0, 0))
        self.labelForLocation.setMaximumSize(QtCore.QSize(175, 16777215))
        self.labelForLocation.setObjectName("labelForLocation")
        self.horizontalLayout_7.addWidget(self.labelForLocation)
        self.filePathDisp = QtWidgets.QLabel(self.centralwidget)
        self.filePathDisp.setObjectName("filePathDisp")
        self.horizontalLayout_7.addWidget(self.filePathDisp)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setObjectName("plainTextEdit")       
        self.verticalLayout_3.addWidget(self.plainTextEdit)
        self.gridLayout.addLayout(self.verticalLayout_3, 2, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Record IR"))
        self.displayFrame.setText(_translate("MainWindow", "Click \"Start IR Camera Feed\" once camera ready."))
        self.startStreamBut.setText(_translate("MainWindow", "Start IR Camera Feed"))
        self.ffcBut.setText(_translate("MainWindow", "Perform FFC"))
        self.label_2.setText(_translate("MainWindow", "Set Gain State:"))
        self.comboGain.setItemText(0, _translate("MainWindow", "HIGH"))
        self.comboGain.setItemText(1, _translate("MainWindow", "LOW"))
        self.comboGain.setItemText(2, _translate("MainWindow", "AUTO"))
        self.label_4.setText(_translate("MainWindow", "Set FFC Mode:"))
        self.comboFFCmode.setItemText(0, _translate("MainWindow", "AUTO"))
        self.comboFFCmode.setItemText(1, _translate("MainWindow", "MANUAL"))
        self.comboFFCmode.setItemText(2, _translate("MainWindow", "EXTERNAL"))
        self.label_3.setText(_translate("MainWindow", "Begin Filename With:"))
        self.filePathBut.setText(_translate("MainWindow", "Select File Path"))
        self.startRec.setText(_translate("MainWindow", "Start Recording Data"))
        self.stopRec.setText(_translate("MainWindow", "Stop Recording/Save"))
        self.recLabel.setText(_translate("MainWindow", "Not Recording"))
        self.displayC.setText(_translate("MainWindow", "Display Celsius"))
        self.displayF.setText(_translate("MainWindow", "Display Fahrenheit"))
        self.timeStatus.setText(_translate("MainWindow", "Time/Date"))
        self.cursorTempLabel.setText(_translate("MainWindow", "Cursor Temp (On Mouse Click)"))
        self.maxTempLabel.setText(_translate("MainWindow", "Max Temperature"))
        self.minTempLabel.setText(_translate("MainWindow", "Min Temperature"))
        self.storageLabel.setText(_translate("MainWindow", "Storage"))
        self.runPost.setText(_translate("MainWindow", "Run Post Processing Script"))
        self.label.setText(_translate("MainWindow", "Command Log:"))
        self.labelForLocation.setText(_translate("MainWindow", "File Save Location:"))
        self.filePathDisp.setText(_translate("MainWindow", "Please Specify Using the Select File Path Button to the Right"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "Notes/Comment Area"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

