# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'postui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1153, 773)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 10, 391, 601))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.selectFileBut_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.selectFileBut_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.selectFileBut_4.setFont(font)
        self.selectFileBut_4.setObjectName("selectFileBut_4")
        self.verticalLayout_6.addWidget(self.selectFileBut_4)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.cmIronBut_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.cmIronBut_4.setObjectName("cmIronBut_4")
        self.horizontalLayout_17.addWidget(self.cmIronBut_4)
        self.cmGrayBut_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.cmGrayBut_4.setObjectName("cmGrayBut_4")
        self.horizontalLayout_17.addWidget(self.cmGrayBut_4)
        self.cmRainBut_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.cmRainBut_4.setObjectName("cmRainBut_4")
        self.horizontalLayout_17.addWidget(self.cmRainBut_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        self.playVidBut_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.playVidBut_4.setEnabled(False)
        self.playVidBut_4.setObjectName("playVidBut_4")
        self.verticalLayout_6.addWidget(self.playVidBut_4)
        self.nextFrame_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.nextFrame_4.setEnabled(False)
        self.nextFrame_4.setObjectName("nextFrame_4")
        self.verticalLayout_6.addWidget(self.nextFrame_4)
        self.prevFrame_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.prevFrame_4.setEnabled(False)
        self.prevFrame_4.setObjectName("prevFrame_4")
        self.verticalLayout_6.addWidget(self.prevFrame_4)
        self.pauseVidBut_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pauseVidBut_4.setEnabled(False)
        self.pauseVidBut_4.setObjectName("pauseVidBut_4")
        self.verticalLayout_6.addWidget(self.pauseVidBut_4)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_22 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_21.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_21.addWidget(self.label_23)
        self.verticalLayout_6.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.startEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.startEdit_4.setEnabled(False)
        self.startEdit_4.setText("")
        self.startEdit_4.setObjectName("startEdit_4")
        self.horizontalLayout_22.addWidget(self.startEdit_4)
        self.stopEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.stopEdit_4.setEnabled(False)
        self.stopEdit_4.setText("")
        self.stopEdit_4.setObjectName("stopEdit_4")
        self.horizontalLayout_22.addWidget(self.stopEdit_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_22)
        self.saveCvImageBut_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.saveCvImageBut_4.setEnabled(False)
        self.saveCvImageBut_4.setObjectName("saveCvImageBut_4")
        self.verticalLayout_6.addWidget(self.saveCvImageBut_4)
        self.makeTiffBut_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.makeTiffBut_4.setEnabled(False)
        self.makeTiffBut_4.setObjectName("makeTiffBut_4")
        self.verticalLayout_6.addWidget(self.makeTiffBut_4)
        self.tempScaleBut_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.tempScaleBut_4.setEnabled(False)
        self.tempScaleBut_4.setObjectName("tempScaleBut_4")
        self.verticalLayout_6.addWidget(self.tempScaleBut_4)
        self.saveAsVideoSS_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.saveAsVideoSS_4.setEnabled(False)
        self.saveAsVideoSS_4.setObjectName("saveAsVideoSS_4")
        self.verticalLayout_6.addWidget(self.saveAsVideoSS_4)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.displayC_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.displayC_4.setEnabled(False)
        self.displayC_4.setObjectName("displayC_4")
        self.horizontalLayout_23.addWidget(self.displayC_4)
        self.displayF_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.displayF_4.setEnabled(False)
        self.displayF_4.setObjectName("displayF_4")
        self.horizontalLayout_23.addWidget(self.displayF_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_23)
        self.maxTempLocLabel_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.maxTempLocLabel_4.setObjectName("maxTempLocLabel_4")
        self.verticalLayout_6.addWidget(self.maxTempLocLabel_4)
        self.maxTempLabel_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.maxTempLabel_4.setObjectName("maxTempLabel_4")
        self.verticalLayout_6.addWidget(self.maxTempLabel_4)
        self.minTempLabel_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.minTempLabel_4.setObjectName("minTempLabel_4")
        self.verticalLayout_6.addWidget(self.minTempLabel_4)
        self.cursorTempLabel_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.cursorTempLabel_4.setObjectName("cursorTempLabel_4")
        self.verticalLayout_6.addWidget(self.cursorTempLabel_4)
        self.minTempLocLabel_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.minTempLocLabel_4.setObjectName("minTempLocLabel_4")
        self.verticalLayout_6.addWidget(self.minTempLocLabel_4)
        self.line_8 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_6.addWidget(self.line_8)
        self.currentFrameDisp_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.currentFrameDisp_4.setObjectName("currentFrameDisp_4")
        self.verticalLayout_6.addWidget(self.currentFrameDisp_4)
        self.currentTimeLabel_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.currentTimeLabel_4.setObjectName("currentTimeLabel_4")
        self.verticalLayout_6.addWidget(self.currentTimeLabel_4)
        self.line_7 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_6.addWidget(self.line_7)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.history = QtWidgets.QPlainTextEdit(Form)
        self.history.setGeometry(QtCore.QRect(10, 620, 391, 141))
        self.history.setObjectName("history")
        self.dispSelectedFile = QtWidgets.QLabel(Form)
        self.dispSelectedFile.setGeometry(QtCore.QRect(550, 10, 601, 17))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dispSelectedFile.sizePolicy().hasHeightForWidth())
        self.dispSelectedFile.setSizePolicy(sizePolicy)
        self.dispSelectedFile.setMinimumSize(QtCore.QSize(601, 17))
        self.dispSelectedFile.setMaximumSize(QtCore.QSize(16777215, 17))
        self.dispSelectedFile.setObjectName("dispSelectedFile")
        self.label_24 = QtWidgets.QLabel(Form)
        self.label_24.setGeometry(QtCore.QRect(410, 10, 134, 17))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setMinimumSize(QtCore.QSize(0, 17))
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.layoutWidget_5 = QtWidgets.QWidget(Form)
        self.layoutWidget_5.setGeometry(QtCore.QRect(412, 39, 731, 631))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.dispLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.dispLayout_3.setContentsMargins(0, 0, 0, 0)
        self.dispLayout_3.setObjectName("dispLayout_3")
        self.layoutWidget_6 = QtWidgets.QWidget(Form)
        self.layoutWidget_6.setGeometry(QtCore.QRect(410, 680, 731, 81))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.sl_3 = QtWidgets.QSlider(self.layoutWidget_6)
        self.sl_3.setEnabled(False)
        self.sl_3.setMinimumSize(QtCore.QSize(739, 0))
        self.sl_3.setOrientation(QtCore.Qt.Horizontal)
        self.sl_3.setObjectName("sl_3")
        self.verticalLayout_8.addWidget(self.sl_3)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.slStartF_3 = QtWidgets.QLabel(self.layoutWidget_6)
        self.slStartF_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.slStartF_3.setObjectName("slStartF_3")
        self.horizontalLayout_28.addWidget(self.slStartF_3)
        self.slMidF_3 = QtWidgets.QLabel(self.layoutWidget_6)
        self.slMidF_3.setAlignment(QtCore.Qt.AlignCenter)
        self.slMidF_3.setObjectName("slMidF_3")
        self.horizontalLayout_28.addWidget(self.slMidF_3)
        self.slEndF_3 = QtWidgets.QLabel(self.layoutWidget_6)
        self.slEndF_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.slEndF_3.setObjectName("slEndF_3")
        self.horizontalLayout_28.addWidget(self.slEndF_3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.slStartT_3 = QtWidgets.QLabel(self.layoutWidget_6)
        self.slStartT_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.slStartT_3.setObjectName("slStartT_3")
        self.horizontalLayout_29.addWidget(self.slStartT_3)
        self.slMidT_3 = QtWidgets.QLabel(self.layoutWidget_6)
        self.slMidT_3.setAlignment(QtCore.Qt.AlignCenter)
        self.slMidT_3.setObjectName("slMidT_3")
        self.horizontalLayout_29.addWidget(self.slMidT_3)
        self.slEndT_3 = QtWidgets.QLabel(self.layoutWidget_6)
        self.slEndT_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.slEndT_3.setObjectName("slEndT_3")
        self.horizontalLayout_29.addWidget(self.slEndT_3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_29)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.selectFileBut_4.setText(_translate("Form", "Select HDF5 File"))
        self.cmIronBut_4.setText(_translate("Form", "Ironblack"))
        self.cmGrayBut_4.setText(_translate("Form", "Grayscale"))
        self.cmRainBut_4.setText(_translate("Form", "Rainbow"))
        self.playVidBut_4.setText(_translate("Form", "Play Video"))
        self.nextFrame_4.setText(_translate("Form", "Next Frame"))
        self.prevFrame_4.setText(_translate("Form", "Previous Frame"))
        self.pauseVidBut_4.setText(_translate("Form", "Pause Video"))
        self.label_22.setText(_translate("Form", "Start Frame:"))
        self.label_23.setText(_translate("Form", "Stop Frame:"))
        self.saveCvImageBut_4.setText(_translate("Form", "Save PNG Image (Without Axes)"))
        self.makeTiffBut_4.setText(_translate("Form", "Generate Tiff File (Full Duration)"))
        self.tempScaleBut_4.setText(_translate("Form", "Generate Figure with Temp Scale"))
        self.saveAsVideoSS_4.setText(_translate("Form", "Save AVI Video from Start to Stop Frame"))
        self.displayC_4.setText(_translate("Form", "Display Celsius"))
        self.displayF_4.setText(_translate("Form", "Display Fahrenheit"))
        self.maxTempLocLabel_4.setText(_translate("Form", "Max Temp Loc:"))
        self.maxTempLabel_4.setText(_translate("Form", "Current Max Temp:"))
        self.minTempLabel_4.setText(_translate("Form", "Current Min Temp: "))
        self.cursorTempLabel_4.setText(_translate("Form", "Cursor Temp:"))
        self.minTempLocLabel_4.setText(_translate("Form", "Min Temp Loc:"))
        self.currentFrameDisp_4.setText(_translate("Form", "Current Frame:"))
        self.currentTimeLabel_4.setText(_translate("Form", "Current Time:"))
        self.label_4.setText(_translate("Form", "Command Log:"))
        self.dispSelectedFile.setText(_translate("Form", "Use Select File Button"))
        self.label_24.setText(_translate("Form", "File Selected: "))
        self.slStartF_3.setText(_translate("Form", "Please Select File"))
        self.slMidF_3.setText(_translate("Form", "Please Select File"))
        self.slEndF_3.setText(_translate("Form", "Please Select File"))
        self.slStartT_3.setText(_translate("Form", "Please Select File"))
        self.slMidT_3.setText(_translate("Form", "Please Select File"))
        self.slEndT_3.setText(_translate("Form", "Please Select File"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

