# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testAppUi.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1027, 560)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.irlabel = QtWidgets.QLabel(self.centralwidget)
        self.irlabel.setGeometry(QtCore.QRect(660, 70, 67, 17))
        self.irlabel.setObjectName("irlabel")
        self.vidBalance = QtWidgets.QLabel(self.centralwidget)
        self.vidBalance.setGeometry(QtCore.QRect(780, 70, 121, 20))
        self.vidBalance.setObjectName("vidBalance")
        self.webcamlabel = QtWidgets.QLabel(self.centralwidget)
        self.webcamlabel.setGeometry(QtCore.QRect(940, 70, 67, 17))
        self.webcamlabel.setObjectName("webcamlabel")
        self.balancer = QtWidgets.QSlider(self.centralwidget)
        self.balancer.setGeometry(QtCore.QRect(660, 90, 351, 21))
        self.balancer.setMaximum(10)
        self.balancer.setSingleStep(1)
        self.balancer.setPageStep(1)
        self.balancer.setProperty("value", 5)
        self.balancer.setSliderPosition(5)
        self.balancer.setOrientation(QtCore.Qt.Horizontal)
        self.balancer.setObjectName("balancer")
        self.cambox = QtWidgets.QGroupBox(self.centralwidget)
        self.cambox.setGeometry(QtCore.QRect(10, 10, 640, 500))
        self.cambox.setObjectName("cambox")
        self.camlabel = QtWidgets.QLabel(self.cambox)
        self.camlabel.setGeometry(QtCore.QRect(6, 26, 640, 480))
        self.camlabel.setText("")
        self.camlabel.setObjectName("camlabel")
        self.pantiltcontroller = QtWidgets.QGroupBox(self.centralwidget)
        self.pantiltcontroller.setGeometry(QtCore.QRect(660, 120, 351, 201))
        self.pantiltcontroller.setObjectName("pantiltcontroller")
        self.adjustbrightness = QtWidgets.QLabel(self.pantiltcontroller)
        self.adjustbrightness.setGeometry(QtCore.QRect(120, 40, 101, 20))
        self.adjustbrightness.setObjectName("adjustbrightness")
        self.LEDSlider = QtWidgets.QSlider(self.pantiltcontroller)
        self.LEDSlider.setGeometry(QtCore.QRect(20, 60, 311, 21))
        self.LEDSlider.setOrientation(QtCore.Qt.Horizontal)
        self.LEDSlider.setObjectName("LEDSlider")
        self.upButton = QtWidgets.QPushButton(self.pantiltcontroller)
        self.upButton.setGeometry(QtCore.QRect(130, 90, 89, 25))
        self.upButton.setObjectName("upButton")
        self.downButton = QtWidgets.QPushButton(self.pantiltcontroller)
        self.downButton.setGeometry(QtCore.QRect(130, 150, 89, 25))
        self.downButton.setObjectName("downButton")
        self.rightButton = QtWidgets.QPushButton(self.pantiltcontroller)
        self.rightButton.setGeometry(QtCore.QRect(220, 120, 89, 25))
        self.rightButton.setObjectName("rightButton")
        self.leftButton = QtWidgets.QPushButton(self.pantiltcontroller)
        self.leftButton.setGeometry(QtCore.QRect(40, 120, 89, 25))
        self.leftButton.setObjectName("leftButton")
        self.startcamButton = QtWidgets.QPushButton(self.centralwidget)
        self.startcamButton.setGeometry(QtCore.QRect(660, 30, 351, 25))
        self.startcamButton.setObjectName("startcamButton")
        self.servoerror = QtWidgets.QPushButton(self.centralwidget)
        self.servoerror.setGeometry(QtCore.QRect(720, 320, 231, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 87, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 87, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 87, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.servoerror.setPalette(palette)
        self.servoerror.setObjectName("servoerror")
        self.camerror = QtWidgets.QPushButton(self.centralwidget)
        self.camerror.setGeometry(QtCore.QRect(720, 360, 231, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 87, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 87, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 87, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.camerror.setPalette(palette)
        self.camerror.setObjectName("camerror")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1027, 22))
        self.menubar.setObjectName("menubar")
        self.menuThermal_Monitor_SR_UI = QtWidgets.QMenu(self.menubar)
        self.menuThermal_Monitor_SR_UI.setObjectName("menuThermal_Monitor_SR_UI")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuThermal_Monitor_SR_UI.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Thermal Monitor (SR) UI"))
        self.irlabel.setText(_translate("MainWindow", "IR"))
        self.vidBalance.setText(_translate("MainWindow", "Video Balance"))
        self.webcamlabel.setText(_translate("MainWindow", "Web cam"))
        self.cambox.setTitle(_translate("MainWindow", "Camera"))
        self.pantiltcontroller.setTitle(_translate("MainWindow", "Pan-tilt Servo Controller"))
        self.adjustbrightness.setText(_translate("MainWindow", "Light Intensity"))
        self.upButton.setText(_translate("MainWindow", "Up"))
        self.downButton.setText(_translate("MainWindow", "Down"))
        self.rightButton.setText(_translate("MainWindow", "Right"))
        self.leftButton.setText(_translate("MainWindow", "Left"))
        self.startcamButton.setText(_translate("MainWindow", "Start Camera"))
        self.servoerror.setText(_translate("MainWindow", "My Pantil Servo does not work!"))
        self.camerror.setText(_translate("MainWindow", "My camera(s) does not work!"))
        self.menuThermal_Monitor_SR_UI.setTitle(_translate("MainWindow", "Thermal Monitor (SR) UI"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

